/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a7955f58-6c34-4d22-9d68-6d8475e1b224",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_mBAmhzKa7",
    "aws_user_pools_web_client_id": "df089efel65drlniedmvj4am6",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "financenews",
            "endpoint": "https://b9lnxoiju5.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
